/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import java.awt.*;

import javax.swing.*;

import Source.Book;

/**
 *
 * @author brianyang
 * @param <bookListPannel1>
 */
@SuppressWarnings("serial")
public class BookListFrame<bookListPannel1> extends JFrame implements DialogClient{

    /**
     * Creates new form MainFrame
     */
	@SuppressWarnings("rawtypes")
	static BookListFrame booklist;
	
    public BookListFrame(String t) {
    	super (t);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        bookListPannel1 = new BookListPannel();
        TopMenuBar = new JMenuBar();
        File = new JMenu();
        AddBook = new JMenuItem();
        AddPage = new JMenuItem();
        Exit = new JMenuItem();
        Help = new JMenu();
        Helps = new JMenuItem();
        About = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new GridBagLayout());

        jPanel1.setBorder(BorderFactory.createEtchedBorder());

        jLabel1.setText("Status");

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 571, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(bookListPannel1, gridBagConstraints);

        File.setMnemonic('F');
        File.setText("File");

        AddBook.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        AddBook.setMnemonic('B');
        AddBook.setText("AddBooks");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	AddBook(evt);
            }
        });
        File.add(AddBook);

        AddPage.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        AddPage.setMnemonic('S');
        AddPage.setText("AddPages");
        AddPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Book newBook =new Book("1000 Songs", "Brian", "1THS", 100);
                AddPage(evt,newBook);
            }
        });
        File.add(AddPage);

        Exit.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        Exit.setMnemonic('E');
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	CloseProgram(evt);
            }
        });
        File.add(Exit);

        TopMenuBar.add(File);

        Help.setMnemonic('H');
        Help.setText("Help");

        Helps.setAccelerator(KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        Helps.setMnemonic('H');
        Helps.setText("Helps");
        Help.add(Helps);

        About.setMnemonic('A');
        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	abouthandler(evt);
            }
        });
        Help.add(About);

        TopMenuBar.add(Help);

        setJMenuBar(TopMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abouthandler(java.awt.event.ActionEvent evt){
    	
    }
    
    private void AddPage(java.awt.event.ActionEvent evt,Book b){
    	AddPageDialog pageDialog =new AddPageDialog(booklist, booklist, b,"add Page to "+b.getName(), true);
    	pageDialog.setVisible(true);
    	
    }
    private void  AddBook(java.awt.event.ActionEvent evt){
    	AddBookDialog bookDialog = new AddBookDialog(booklist, booklist,"Add a new Book",true);
    	bookDialog.setVisible(true);
    	
    	
    }
    private void CloseProgram(java.awt.event.ActionEvent evt){
    	System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	BookListFrame booklist =new BookListFrame("Book List ");
            	booklist .setVisible(true);
                GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().setFullScreenWindow(booklist);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenuItem About;
    private JMenuItem AddBook;
    private JMenuItem AddPage;
    private JMenuItem Exit;
    private JMenu File;
    private JMenu Help;
    private JMenuItem Helps;
    private JMenuBar TopMenuBar;
    private GUI.BookListPannel bookListPannel1;
    private JLabel jLabel1;
    private JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

	@Override
	public void dialogFinished(operation anOperation) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void dialogCancelled() {
		// TODO Auto-generated method stub
		
	}
}
