/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PageListPannel.java
 *
 * Created on Jan 7, 2014, 6:27:53 PM
 */
package GUI;

import bookviewer.Book;
import bookviewer.Page;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.JList;

/**
 *
 * @author byang1
 */
public final class PageListPannel extends javax.swing.JPanel {

    /** Creates new form PageListPannel */
    MouseListener doubleClickBookListListener;
    MouseListener doubleClickPageListListener;
    
    ArrayList<Book> bookCollection;
    ArrayList<Page> pageCollection;
    
    Book            selectedBook;
    Page            selectedPage;
    
    
    
    public PageListPannel(MouseListener doublePageListener, MouseListener doubleBookListener,
                           ArrayList<Book> books, ArrayList<Page> pages) {
        doubleClickPageListListener =doublePageListener;
        doubleClickBookListListener =doubleBookListener;
        
        bookCollection = books;
        pageCollection = pages;
        selectedBook = null;
        selectedPage = null;
        initComponents();
        
        
    }
    public void enableListener(){
        this.BookList.addMouseListener(doubleClickBookListListener);
        this.PageList.addMouseListener(doubleClickPageListListener);
    }
    public void disableListener(){
        this.BookList.removeMouseListener(doubleClickBookListListener);
        this.PageList.removeMouseListener(doubleClickPageListListener);
    }
    
    
    private void updateList(){
        Book bookArray[] = new Book[1]; //just to establish array type
	    getBookList().setListData(((Book []) bookCollection.toArray(bookArray)));
        Page pageArray[] = new Page[1]; //just to establish array type
	    getPageList().setListData(((Page []) pageCollection.toArray(pageArray)));
            
            if (selectedBook != null)
			getBookList().setSelectedValue(selectedBook, true);
		if (selectedPage != null)
			getPageList().setSelectedValue(selectedPage, true);
    }

    

    
    public JList getBookList(){
        return BookList;
    }
    
    public JList getPageList(){
        return PageList;
    }
    
    public void setBookList(ArrayList<Book> books){
        if(books!=null) bookCollection = books;
       
    }
    public void setPageList(ArrayList<Page> pages){
       if(pages!=null) pageCollection = pages;
       if(pages == null)  pageCollection.removeAll(pageCollection);
    }
    public void setBookList(ArrayList<Book> books,Book b){
       if(books == null) bookCollection.removeAll(bookCollection);
        selectedBook = b;
       
    }
    public void setPageList(ArrayList<Page> pages, Page p){
        if(pages == null)  pageCollection.removeAll(pageCollection);
        if(pages!=null) pageCollection = pages;
        selectedPage = p;
       
    }
 
    public void update(){
        disableListener();
        updateList();
        enableListener();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BookList = new javax.swing.JList();
        Book = new javax.swing.JLabel();
        SeachTextField = new javax.swing.JTextField();
        seachButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PageList = new javax.swing.JList();

        BookList.setBorder(javax.swing.BorderFactory.createTitledBorder("Book List"));
        BookList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(BookList);

        Book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/book.png"))); // NOI18N

        seachButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/search32.png"))); // NOI18N
        seachButton.setText("Search Page");
        seachButton.setToolTipText("Search Page");

        PageList.setBorder(javax.swing.BorderFactory.createTitledBorder("Page List"));
        PageList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(PageList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Book)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(SeachTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seachButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SeachTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seachButton))
                    .addComponent(Book))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Book;
    private javax.swing.JList BookList;
    private javax.swing.JList PageList;
    private javax.swing.JTextField SeachTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton seachButton;
    // End of variables declaration//GEN-END:variables
}
