/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BookListPannel.java
 *
 * Created on Jan 7, 2014, 5:39:01 PM
 */
package viewer;

import javax.swing.JPanel;


/**
 *
 * @author byang1
 */
public class BookListPanel extends JPanel {
    
    
    /** Creates new form BookListPannel */
    public BookListPanel() {
       
        initComponents();
       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BookListScroll = new javax.swing.JScrollPane();
        BookList = new javax.swing.JList();
        seachTextField = new javax.swing.JTextField();
        seachButton = new javax.swing.JButton();
        Book = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        BookList.setBorder(javax.swing.BorderFactory.createTitledBorder("Book List"));
        BookList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        BookListScroll.setViewportView(BookList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(BookListScroll, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        add(seachTextField, gridBagConstraints);

        seachButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/search32.png"))); // NOI18N
        seachButton.setText("SearchBook");
        seachButton.setToolTipText("Search Book");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(seachButton, gridBagConstraints);

        Book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/book.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(Book, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Book;
    private javax.swing.JList BookList;
    private javax.swing.JScrollPane BookListScroll;
    private javax.swing.JButton seachButton;
    private javax.swing.JTextField seachTextField;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getBook() {
        return Book;
    }

    public void setBook(javax.swing.JLabel Book) {
        this.Book = Book;
    }

    public javax.swing.JList getBookList() {
        return BookList;
    }

    public void setBookList(javax.swing.JList BookList) {
        this.BookList = BookList;
    }

    public javax.swing.JButton getSeachButton() {
        return seachButton;
    }

    public javax.swing.JTextField getSeachTextField() {
        return seachTextField;
    }

}
